import type { ComponentProps } from '@shared/schema'
export const COMPONENT_NAME_MAPPING = {
  Image: '图片',
  Panel: '自然布局',
  Container: '容器',
  Dialog: '高级对话框',
  Tabs: '选项卡',
  HybirdTable: '表格',
  RelationTable: '母子表格',
  Filter: '查询筛选',
  GroupTable: '分组表格',
  EvelatorForm: '电梯表单',
  NormalForm: '高级表单',
  StepForm: '步骤表单',
  Pie: '饼图',
  Square: '条形图',
  Circle: '环形图',
  Line: '折线图',
  Ask: '对话框',
  Button: '按钮',
  MenuButton: '菜单按钮',
  ButtonGroup: '按钮组',
  SplitLine: '分隔线',
  Icon: '图标',
  Link: '链接',
  Text: '输入框',
  TextArea: 'TextArea',
  Number: '数字输入框',
  Price: '价格输入框',
  Qty: '数量输入框',
  Password: '密码框',
  Date: '日期选择框',
  DateRange: '日期区间',
  Radio: '单选按钮',
  RadioGroup: '单选按钮组',
  SCheckbox: '复选按钮',
  CheckboxGroup: '复选按钮组',
  Address: '地址级联',
  Switch: '开关组件',
  SSelect: '下拉选择器',
  Tips: '提示',
  Search: '搜索',
  CategorySearch: '分类搜索',
  Operation: '操作列',
  Upload: '上传组件',
  Custom: '低代码组件',
  FormItem: '表单插槽',
}
export const COMPONENT_DEFAULT_PROPS: ComponentProps = {
  /**cid: '',
  parent: '',*/
  name: '',
  label: '标签标题',
  //size: 1,
  //device: 2,

  //form item props
  tip: false,
  /**errTip: '',
  helpTip: '',*/
  //validateStatus: 1,
  autoValidate: false,
  defaultVal: '',
  placeholder: '',
  maxLength: Infinity,
  clear: false,
  //require: false,
  //disable: false,
  //readonly: false,
  //hover: false,
  //trim: true,
  border: true,
  //focus: false,
  //showIcon: false,

  //tabStatus: 1,
  //tabLayout: 2,
  labelPos: 'left',
  labelAlign: 0,

  //isContainer: false,
  //isPanel: false,
  //parentDirect: 'column',

  inlineStyle: {},

  //inTable: false,
  isLowCode: false,
}
